name: Build and Deploy Java App

on: push

jobs:
  build:
    name: Build and Run Application
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Create Docker network
        run: |
          docker network create --driver bridge se-methods
          docker pull mongo
          docker run -d --name mongo-dbserver --network se-methods mongo

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t se_methods .

      - name: Run Docker container
        run: docker run --network se-methods --name semcontainer se_methods

      - name: View logs
        run: docker logs semcontainer
